---
title: "Installation"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

You can install STREAM via below commands:
```{r, eval=FALSE}

# First, check and install the dependency packages using cran
cran_packages <- c("data.table", "dplyr", "ggplot2", "igraph", "Matrix", 
                   "pbapply", "qgraph", "RColorBrewer", "RCurl", "Ryacas",
                   "easypackages", "enrichR", "pbmcapply", "qualV",
                   "scales", "stats", "utils"
                   )

to_install_cran <- cran_packages[!sapply(cran_packages, requireNamespace, quietly = TRUE)]
if (length(to_install_cran) > 0) {
    install.packages(to_install_cran)
}


# Second, check and install BiocManager has been installed
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")


# Third, check and install the dependency packages by BiocManager
bioc_packages <- c("AnnotationDbi", "BSgenome", "BSgenome.Hsapiens.UCSC.hg19", "BSgenome.Hsapiens.UCSC.hg38", 
                   "BSgenome.Mmusculus.UCSC.mm10", "EnsDb.Mmusculus.v79", "EnsDb.Hsapiens.v75", 
                   "EnsDb.Hsapiens.v86", "biomaRt", "ensembldb", "GenomeInfoDb", "GenomicAlignments", 
                   "GenomicRanges", "JASPAR2022", "motifmatchr", "Repitools", "regioneR", 
                   "rTRM", "SingleCellExperiment", "STRINGdb", "SummarizedExperiment", 
                   "IRISFGM", "simpIntLists", "TFBSTools"
                   )

to_install_bioc <- bioc_packages[!sapply(bioc_packages, requireNamespace, quietly = TRUE)]
if (length(to_install_bioc) > 0) {
    BiocManager::install(to_install_bioc)
}


# Fourth, check and install devtools
if (!requireNamespace("devtools", quietly = TRUE))
    install.packages("devtools")


# Fifth, check and install the dependency packages by devtools
github_packages <- c( 
                     "mskilab-org/gUtils",  
                     "cole-trapnell-lab/monocle3", 
                     "satijalab/Seurat", 
                     "satijalab/Signac"
                     )

# Extracting package names from GitHub paths
package_names_github <- sapply(strsplit(github_packages, "/"), `[`, 2)

to_install_github <- github_packages[!sapply(package_names_github, requireNamespace, quietly = TRUE)]
if (length(to_install_github) > 0) {
    devtools::install_github(to_install_github)
}


# Sixth, install STREAM
devtools::install_github("YangLi-Bio/stream2")

```


```{r, echo=FALSE}

message ("Skipping installation of 'stream2' and its dependencies from a github remote")

```


```{r}

# Check session information
sessionInfo()

```
